### PR TITLE
info.txt for version checker.

### PR DESCRIPTION
**Pull request by Servius**

### CODE REVIEW

**Comment by Servius** [comment]
I have a version checker ready to go. I cant set it up without the link being created once this is accepted though.

**Comment by Liam0102** [comment]
Surely a version checker isn't relevant for an addon that is updated automatically via Steam?

**Comment by Servius** [comment]
Youd think so. Youd be surprised how many server owners arent capable of basic bug fixing. Its an on server start up check thatll go off and double check with the git repo that everything is up to date. 

Its not a major addition nor will it be extreme levels of helpful. If anything we have it be coupled with a changelog we can update here.

**Comment by Servius** [comment]
Id love to add a way for players to trigger it locally via a tools menu tab but that would be a later step.

**Comment by Liam0102** [comment]
But the Git Repo isn't supposed to be measured against. It's an in-development version of the addon. Not to mention you can't compile .txt files into a .gma (At least not on Mac)

**Comment by Servius** [comment]
Im not saying compile the .txt into the gma. Itll check back here, in the git repo, when we manually change the .txt files version number. Really just wanted to provide a way for people to keep track with whats changed from version -> version which starts with a version checker.

**Comment by Liam0102** [comment]
Alright, I'm going to accept this but it's up to you to maintain. I'm not going to remember to update it every time I make a change.

**Comment by Servius** [comment]
Thats fine. Would really only be done on major significant things. Like when we think "Oh hey, time for a changelog so people no what weve done since the last version"

**Comment by Servius** [comment]
Thank you for merging!

**Pull request merged**
