### PR TITLE
Adding icons and HUD files from the live addon. 

### PR DESCRIPTION
**Pull request by Servius**
## **What this pull request does**
- Adding icons and HUD files from the live addon. 

### **Changes are intended for a later update.**

- I'll be converting the vtf files ( after work tonight probably ) for the entity icons to png files and then put all the png files through some minimal compression which will not affect visual quality but will reduce overall size from 20-25mb down to hopefully 4-7mb. 
- I will also be adding one or two new ship categories as some of my vehicles are weird af and there are enough of them to qualify for their own little tab.

### CODE REVIEW

**Comment by Liam0102** [comment]
I didn't include the materials on here for a reason. That reason being size.

**Comment by Servius** [comment]
So when I make changes to them I should do?

**Comment by Liam0102** [comment]
Considering the spawn icons as you mentioned aren't actually 20mb but 200kb, I'd suggest nothing.

**Comment by Servius** [comment]
http://image.prntscr.com/image/5ac34da44cee449c89af3d63e5b618a8.png

**Comment by Servius** [comment]
22.2-4 mb is the current collective size of what I was looking to add and then later compress.

**Comment by Servius** [comment]
I was looking to lower that collective size to 4-7 mb. I was also looking to add new tab icons.

**Comment by Servius** [comment]
@Liam0102 alt text
I have only done the spawn icons so far. I've given them [transparency](http://image.prntscr.com/image/4d2d118963054eb2a4bcd9b42e1da09c.png) which should be visually better looking. I could reduce the size a bit more but that would result in a loss of image quality. 

Are you okay with me adding the spawn icons and the other png files for the hud stuff? Since they are things that we could potentially replace/add to it seems like it wouldn't hurt to have them in the repo. I can understand not having models/mats for the vehicles as those would completely bloat the download.

**Comment by Servius** [comment]
@Liam0102 Hello?

**Pull request closed without merging**
