### PR TITLE
Update #14

### PR DESCRIPTION
**Pull request by Servius**
- Organized the addon specific folders into one folder. Did this to avoid any issues while updating the live addon. 
- Added the **POST**-compression spawn icons. Should reduce live addon size from **[79.512 MB](http://image.prntscr.com/image/0bd32cc369a94ddda9c04db3a3f06d71.png)** to hopefully 75~ MB. _NOTE: Will try to continue to do these type of updates to hopefully drive down the file size of the download without hurting the quality of the addon._ 
- Vehicle template added. Will expand and formatted more over time. Initial addition. 
- Readme added. Im probably only going to bold it later but its really just supposed to declare to the universe "READ THE VEHICLE TEMPLATE" if they want to create a new vehicle. I might add instructions on how to use git.

### CODE REVIEW

**Comment by Servius** [comment]
@Liam0102

**Comment by Liam0102** [comment]
Why are you moving files into "addon specific"?

**Comment by Servius** [comment]
Thou

**Comment by Servius** [comment]
On my phone. Accidntal close on my end.


Thought it would be easier to navigate the repository if moved the addon stuff like the json, .txt, lua files, and mats away from any potential files that we wouldnt want accidentally uploaded to the live addon.

**Comment by Servius** [comment]
Like the readme and template.

**Comment by Liam0102** [comment]
Not necessary, not to mention the template shouldn't be included in this GIT. This specifically for the development of the Episode 1. The template can be linked to, but shouldn't be included.

Image files are fine (All though I doubt the HUD elements need work), and honestly a Readme with one line in it isn't really worth it.

**Comment by Servius** [comment]
Was just thinking of convience regarding the template. Wouldnt it be a bit silly to have a whole new repo created just for one file. 

I intend to update the readme later but adding it now will give syph, doc, randoms, and yourself the option to update it with relavent information in the mean time.

**Comment by Servius** [comment]
But you are right. This isnt exactly the most amazing update ever. Just setting groundwork for stuff thatll help later down the road.

**Comment by Liam0102** [comment]
The template doesn't need to be hosted here. I already have it on my dropbox, it can just be linked to. I'm going to close this, but if you want to open a new one with just the image files and the readme that's up to you.

**Comment by Servius** [comment]
Iphones charging are annoying af.

Anyways, Id like to be able to add more information (like the commenting and formatting i added to the few sections i was able to do in the time i had available tonight) so others (or myself when i cant remember how to do something) have an easier time adding more advanced functionality not currently documented (like seats or first person view overlays) elsewhere. 

I believe you could have split the pull request and only accept the portions you were okay with

**Pull request closed without merging**
